ci: install libx11-dev for Vortek client build
vulkan.h pulls in X11/Xlib.h when VK_USE_PLATFORM_XLIB_KHR is defined
(set by build-vortek-client.sh's cflags), which isn't provided by
libvulkan-dev. Failed with:
  /usr/include/vulkan/vulkan.h:58:10: fatal error: X11/Xlib.h: No such file or directory